---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.11.3
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  # https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/deployment/helm/node-feature-discovery/values.yaml
  values:
    nodeFeatureRule:
      createCRD: true
    worker:
      annotations:
        configmap.reloader.stakater.com/reload: node-feature-discovery-worker-conf
      config:
        core:
          sources:
            - custom
            - pci
            - usb
        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              - "03"
              - "0e"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - class
              - vendor
              - device
          # https://github.com/kubernetes-sigs/node-feature-discovery/tree/master/deployment/overlays/samples/custom-rules
          custom:
            ### GPUs ###
            # `lspci | grep VGA`
            - name: "intel-gpu"
              matchOn:
                - pciId:
                    vendor: ["8086"]
                    class: ["0300"]
