---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-intel-gpu-plugin
  namespace: flux-system
spec:
  path: ./kubernetes/apps/system/intel-gpu/plugin
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: intel-gpu-plugin
      namespace: system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-intel-gpu-exporter
  namespace: flux-system
spec:
  path: ./kubernetes/apps/system/intel-gpu/exporter
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: intel-gpu-exporter
      namespace: system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
