bgp:
  enabled: false
hubble:
  enabled: false
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: 10.244.0.0/16
securityContext:
  privileged: true

k8sServiceHost: "192.168.10.200"
k8sServicePort: 6443
