---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/home-assistant
      tag: 2023.4.2
    env:
      TZ: ${TIMEZONE}

    podAnnotations:
      secret.reloader.stakater.com/reload: *app
      k8s.v1.cni.cncf.io/networks: macvlan-static-iot-hass

    dnsConfig:
      options:
        - name: ndots
          value: "1"

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_HASS_ADDRESS}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        # annotations:
        #   external-dns.home.arpa/enabled: "true"
        hosts:
          - host: &host "home.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-pvc

    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 750Mi

    nodeSelector:
      worker-node: "true"
