kind: ENC[AES256_GCM,data:WhfBJ6d9,iv:Dd2KHMiSMzPbssF927232SCURN9sGd877bv6HLvw5EY=,tag:yPwfOihwu158L/Tcm4tl/Q==,type:str]
ansible_user: ENC[AES256_GCM,data:66Gi9BOj,iv:SPNHZSOHnfFLzUdIho0yv7QBLvCtnHpLoKZ9+U55csU=,tag:u34/p8LQ9vrR/IFY7zEgFg==,type:str]
ansible_become_pass: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age153gpfdw58csvgxj3vn9ym2g3zx7mfhaldyz5uvvrfajne8htj3asjqrp7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MlpqT01hUzFxMVdOTUEv
            ek1JK2RURDh4V21oOUJYU2ozeFR1N3lqMkhvCldmS09SZHkrQmtxREFXM3VsOHJq
            cUtJZExrNEx5ZU5naW1vdHZXKzd6bGcKLS0tIFA2NEpyUXp3SHJtSk1vb0lvUzNx
            T1RuWW9FNmpObW1nYWFub3NaSGpBVlEK/awmYegNyept7qNJrFuAMvfhJ0bmd+SE
            XX8eNQgzIJT7Ebx3dD6cfbQAB13C1W1M9Hg0EFNBqht+XMGUIlkDXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T02:24:37Z"
    mac: ENC[AES256_GCM,data:efdA5ARGlczdkJhQrV5CkjG9H9ArufGOJrVkYr5V2klj7hQ1Suk707atnkFr3tzVLgI3cu073Ag1GHbD9PldZBs9M0Ih9DS8WTaIV4xOLp+Qc9JYPNmwoBGFaCYRkE9QkFBp1ktYECxegQf473LRmz6vZVTlkrBswPgodGzEz+k=,iv:DPdqscNRPui/4/IYslSo1+ir3pjzFoEBS+0XTL4QHps=,tag:kLOBc1y0HoqH0b59CisT/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
