---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: openebs
      version: 3.4.1
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
      interval: 10m
  values:
    legacy:
      enabled: false
    cstor:
      enabled: false
    ndm:
      enabled: false
    ndmOperator:
      enabled: false
    nfs-provisioner:
      enabled: false
    mayastor:
      enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mayastor
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: mayastor
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: mayastor
        namespace: flux-system
      interval: 10m
