---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mayastor
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: mayastor
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: mayastor
        namespace: flux-system
      interval: 10m

