---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    labels:
        app.kubernetes.io/name: grafana
type: Opaque
stringData:
    gf_security_admin_user: ENC[AES256_GCM,data:qgnpsJnaLA==,iv:uX7joQrq2EleYL9OUlaZ6mAnYPBpAc5sWyxCKuuz+a0=,tag:dnzxqDE8eFNcUNpr7mPwdg==,type:str]
    gf_security_admin_password: ENC[AES256_GCM,data:5VQuQdvofYE/cnVTDxiI4qJZfg==,iv:WwnMWcqZ1BYv+fCAfqyrELJObzThJNP5ANRkQgKjdwI=,tag:/EZzsJxxVzgqlNIZSFMpbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age153gpfdw58csvgxj3vn9ym2g3zx7mfhaldyz5uvvrfajne8htj3asjqrp7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eXJaQWUwbnlVdlc4b2kz
            ZlRROTZXM3E3QXNtbnFseEd6ZU1nYjNvWXhzCnFmTml3bldIMUhoTDZvQ3l1L3hR
            OVBQZ0E3anRNVk81NEZFdWkzckhKeGsKLS0tIHB5OG9tSTZpRjR3dlZ4Ykw0M3pF
            UTh5V25aMHRtN2FqWjBMd3dNRGVvNUUKsjVgtV/qqQdBI7cBbmdKFs8i2xmP6EaW
            GYV/Wj6BA7VdfxPXnGNgni0AnM+wSlvGl4XDJXKt12HTO4BWPT5aGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-04T02:20:55Z"
    mac: ENC[AES256_GCM,data:ao4TA33mNZVjhdFEdx5+fGEZQ65Qzf5Wyk/mWDkQQ1grQHGyE0//gsFCuu8mYlDI6uY7iGRpkxurjn0wpDk42sj5x/L0k6UUyl/o3mLryBHkJF993zHbL54u1tycl70Jy7ppYn6kgPH9FGsG9PQ+h+PTy9bmlYr0grcr2stGQnc=,iv:Xg9J1x8SinqpbiwQD29AqnGt7ZnPjeXfawMvlsMEViQ=,tag:aS6v3M/M0ZJHJngn8d/lYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
