---
kubernetes:
  children:
    master:
      hosts:
        k8s-cp01:
          ansible_host: 192.168.10.201
        # k8s-cp02:
        #   ansible_host: 192.168.10.202
        # k8s-cp03:
        #   ansible_host: 192.168.10.203
    worker:
      hosts:
        k8s-wk01:
          ansible_host: 192.168.10.204
        # k8s-wk02:
        #   ansible_host: 192.168.10.205
        # k8s-wk03:
        #   ansible_host: 192.168.10.206
