---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app xen-orchestra
  namespace: system
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: docker.io/ronivay/xen-orchestra
      tag: 5.111.1@sha256:b32a2da1b2de5c05f533d8ecc333ff1735a02ddb363539389dd9e8942bd8bfa1
    env:
      TZ: ${TIMEZONE}
      HTTP_PORT: &port 80

    podAnnotations:
      secret.reloader.stakater.com/reload: *app

    service:
      main:
        ports:
          main:
            procotol: HTTPS
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "xo.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    persistence:
      config:
        enabled: true
        existingClaim: xen-orchestra-config-pvc
        mountPath: "/var/lib/xo-server"
      redis:
        enabled: true
        existingClaim: xen-orchestra-redis-pvc
        mountPath: "/var/lib/redis"

    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0

    securityContext:
      readOnlyRootFilesystem: false
      runAsNonRoot: false
      capabilities:
        add:
          - SYS_ADMIN

    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 750Mi

    nodeSelector:
      worker-node: "true"

    portal:
      enabled: true
