---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app xen-orchestra
  namespace: system
spec:
  interval: 15m
  chart:
    spec:
      chart: xen-orchestra
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: true-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: tccr.io/truecharts/xenorchestra
      tag: 5.109.0@sha256:c20120d537153808f055a4b396e5095f026f2ae408fdcca3c4f7072fac4d0b7b
    env:
      TZ: ${TIMEZONE}
      HTTPS_PORT: &port 10324
      # Just so it doesn't try to bind port 80
      HTTP_PORT: *port
      REDIRECT_TO_HTTPS: true

    podAnnotations:
      secret.reloader.stakater.com/reload: *app

    service:
      main:
        ports:
          main:
            procotol: HTTPS
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    persistence:
      config:
        enabled: true
        existingClaim: xen-orchestra-config-pvc
        mountPath: "/var/lib/xo-server"
      redis:
        enabled: true
        existingClaim: xen-orchestra-redis-pvc
        mountPath: "/var/lib/redis"

    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0

    securityContext:
      readOnlyRootFilesystem: false
      runAsNonRoot: false
      capabilities:
        add:
          - SYS_ADMIN

    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 750Mi

    nodeSelector:
      worker-node: "true"

    portal:
      enabled: true
