---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xen-orchestra-config-pvc
  namespace: system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-double-replica
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xen-orchestra-redis-pvc
  namespace: system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: openebs-double-replica
