---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: 1.13.1
      sourceRef:
        kind: HelmRepository
        name: cilium-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    bgp:
      enabled: false
    ipam:
      mode: kubernetes
    ipv4NativeRoutingCIDR: 10.244.0.0/16
    securityContext:
      privileged: true
    k8sServiceHost: "192.168.10.200"
    k8sServicePort: 6443
