---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cilium-charts
      version: 1.13.2
  interval: 1m0s
  values:
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    cluster:
      id: 1
      name: home-cluster
    ipam:
      mode: kubernetes
    ipv4NativeRoutingCIDR: 10.244.0.0/16
    k8sServiceHost: 192.168.10.250
    k8sServicePort: 6443
    kubeProxyReplacement: strict
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
      privileged: false
