cluster:
  name: home-cluster
  id: 1
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: 10.244.0.0/16
k8sServiceHost: "192.168.10.250"
k8sServicePort: 6443
kubeProxyReplacement: strict
securityContext:
  privileged: true
