---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs-cstor
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: openebs
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
      interval: 10m
  values:
    legacy:
      enabled: false
    cstor:
      enabled: true
    nfs-provisioner:
      enabled: true
    # Required when using the same device that hosts the OS FS partition
    openebs-ndm:
      enabled: true
