---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-media
  namespace: openebs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "openebs-kernel-nfs"
  resources:
    requests:
      storage: 20Ti
