---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k10
  namespace: kasten-io
spec:
  releaseName: k10
  interval: 5m
  chart:
    spec:
      chart: k10
      version: 5.5.6
      sourceRef:
        kind: HelmRepository
        name: kasten-charts
        namespace: flux-system
      interval: 5m
  values:
    eula:
      accept: true
      company: Strallow
      email: "{SECRET_CLOUDFLARE_EMAIL}"
    global:
      persistence:
        storageClass: openebs-triple-replica
    auth:
      k10AdminUsers:
        - "{SECRET_CLOUDFLARE_EMAIL}"
      oidcAuth:
        enabled: true
        secretName: kasten-secret
    clusterName: k8s
    ingress:
      create: true
      class: nginx
      host: "k10.${SECRET_DOMAIN}"
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      urlPath: k10
      hosts:
        - "k10.${SECRET_DOMAIN}"
      tls:
        enabled: true
        secretName: "tls.k10"
    grafana:
      enabled: false
