apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:GUtKA9eJ7mC7XzbcTcBpre8P,iv:J1MIMc9FNnIeCTbzRKKLBvY9b0rfDWMP1rS/y/OzNNk=,tag:S0Y/qWXPOP0QZONhuGIgRg==,type:str]
    api-key: ENC[AES256_GCM,data:B5cZSX3OXIUNykntiN4l2bZks4cC2nVFfm8v5ypooi0xoCSJOg==,iv:rn03FvYT0onLflQ7a/WGAFk2/jd5b7ZTrjFQPqGMctc=,tag:+RHOUHR7Zz3cpM5kalLuag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age153gpfdw58csvgxj3vn9ym2g3zx7mfhaldyz5uvvrfajne8htj3asjqrp7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaEhrc1o0STJFUTBvWERu
            MGpTS2dac1hVZkxOejF2Z2JrRHFQeVY2WHd3CkJyMENzNjhFamlRV0FjYUh4dWli
            TXg3ZUtFMEpIaVdGZmRSazQrUlVKbnMKLS0tIG11RU5scU54ZGZxWE5NY3duVlYw
            aVpKVExqZHcxRmVuMDlBT2Zib25qT0UKFxJg5XkpW2CaIGhDp0FhKeyHqsG6cFf7
            kAtX7i0DJ4iej0gdhS+jJxrFsvozZ+skYGh+5oPL+708BIOhJM1ozQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-04T11:59:53Z"
    mac: ENC[AES256_GCM,data:hGa4/miIWy/UF4kxDPg1L1CUax3QFIc8TrVropF0rCAXxphH6W3TGYzFNkM4+C3Hnr+54DRkzKVRGtIQx0rgYV11XoqhHcdhsvOD8vFfi2oQDG9xusxKB3xqHdBhioQIoQ9UEU58cHb2K+Lel6dX7HDD46QanPtwtybj1/yrDgU=,iv:5sYj0y49pxuuk6VpvbETDR08CXv2h76sXXJjoufxWrg=,tag:k1WkZhwnMsGnanB5GPNVDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
