---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app tinymediamanager
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: tinymediamanager/tinymediamanager
      tag: latest

    env:
      TZ: ${TIMEZONE}

    service:
      main:
        ports:
          http:
            port: &port 4000

    probes:
      liveness: &probes
        enabled: true
      readiness: *probes
      startup:
        enabled: false

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        # annotations:
        #   auth.home.arpa/enabled: "true"
        #   external-dns.home.arpa/enabled: "true"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: tinymediamanager-data-pvc
      nfs-nas-media:
        enabled: true
        existingClaim: media-nfs-share-pvc
        mountPath: /mnt/data/media-data
        readOnly: false

    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 500Mi

    nodeSelector:
      worker-node: "true"
