---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-xen-orchestra
  namespace: flux-system
spec:
  path: ./kubernetes/apps/system/xen-orchestra/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: xen-orchestra
      namespace: system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
