apiVersion: v1
kind: Secret
metadata:
    name: prowlarr
    namespace: media
type: Opaque
stringData:
    PROWLARR__API_KEY: ENC[AES256_GCM,data:RRRoAIcaTgB1SzHXGDJ1rlkcr3YunpImS9xjLgnY3Kk=,iv:trWjAOgZDYLgJP6VQ68oh7kQuTcdxvtxNRTL2FU7IXU=,tag:V/s096cPuGSv8vNm+pUVXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age153gpfdw58csvgxj3vn9ym2g3zx7mfhaldyz5uvvrfajne8htj3asjqrp7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZXIxQmFNeTBXZEpRWjFa
            YllSTmd2QmFsMzIyVjF5T1c5MVJJck95M2t3CkZvaW9tOHBaUlhLZGlrcGtQd0NY
            R2lSQ2swVmp6OWxxN0VyZGN0ZS8xZUEKLS0tIFEydnE4ZGVWZ2RJRHBtZmRiV1hs
            VU9DYWJET1lmckw0aEdXUW01ZThMRFkKwZstSD0irUmhfTA1sUn9DTyV3VK0hCkT
            vgdfxP0UWxBP/N6arxFvySX4TBBZJiSN4JFc4DS9v9tzAKMiIOeVLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-08T06:58:21Z"
    mac: ENC[AES256_GCM,data:kyESO0CHkTryQSIulO0nSeg0zttDy2kZKONoaFcoD2b3Jxd9EJqpXckl8MGVbL6DnEP3fQE4FEJOym6iSQ7FO0s/JLqntU9pTnaOae2xyHwTiTHqkupX+78iCgmt8tPk/HOwvbDOFg6JSwppi7Mqo3LC3c91WvlR7e1Pcmue+O8=,iv:n1/yhGq37YIRLhVZKshEeX0cBVvmzl0oT1FVtKU/IZw=,tag:8t1/7ffVDT1TPla2BjfY4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
