---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-media-browser
  namespace: flux-system
spec:
  path: ./kubernetes/apps/media/media-browser/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: media-browser
      namespace: media
  interval: 30m
  retryInterval: 1m
  timeout: 3m
