---
apiVersion: k8s.nginx.org/v1alpha1
kind: GlobalConfiguration
metadata:
  name: nginx-configuration
  namespace: networking
spec:
  listeners:
    - name: rpcbind
      port: 111
      protocol: TCP
    - name: nfs
      port: 20490
      protocol: TCP
