apiVersion: v1
kind: Secret
metadata:
    name: radarr
    namespace: media
type: Opaque
stringData:
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:vgfm2b171VPR5igrABBf0PugjEd8qhtf/PHyONhe,iv:KzV3TFM+S9UMctTFon1kr/OuoMqSxG5ybfNMBAA0Ab0=,tag:ENwop2qfpj2LXFjrFaAXFg==,type:str]
    PUSHOVER_USER_KEY: ENC[AES256_GCM,data:YbgsKCgEobwM4ugTcTcoY6Ib4uxpJoOlrmfUGfBV,iv:J8XNQzGC5TSLs2VLsozY+tPQcCK2kJe+xHaYfN6RPYE=,tag:I0LlhFfYzCVoDXFEt5VS0w==,type:str]
    RADARR__API_KEY: ENC[AES256_GCM,data:LvzmMxOcbC1upJ/Ha8aOKXAdojgY060eD590A2rJILc=,iv:re75w5OuA34BCy7+53okRpr1206lvIMi0IQtgaD90xY=,tag:4QOZRuOt2aAC5XdcaE22jA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age153gpfdw58csvgxj3vn9ym2g3zx7mfhaldyz5uvvrfajne8htj3asjqrp7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxamxsWEtydnQwVWxwWUUz
            Q2htUFNRUzRTSExFdWRwZU0yekl2NEpac0MwCnlWVUJkRUFSMXROOStiNmJUOUZB
            Zk1SU0dubTJ0V21lV0U5Lzl5Y0ZWSk0KLS0tIEx4WVIxT29pejZrRWtNdzhQRXNV
            UURuN3lvVUx6SjkwSXBFUUtqOEpkOW8Kt4lcuisJ09ou/SEsWtWsdvjNXJ7F//1p
            BWMTNV5RfTEH1Zlrv5Bv9k9SR3d7O0oxfH8mh6P2GE4kn1WXGp6Lug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-07T21:47:08Z"
    mac: ENC[AES256_GCM,data:5gV+9lD3R4k17WCifr4uROaiy29wYZKZ/aIXuJWp2WHuvo5ElB6/wDcKV7k6pxOmXhOWr1KKuDenzCYSCku5ymVO3+cv5keYzT3Z71AdRUPRbvh8xA/H1UgltWzd6UagyuXiUQ+2qrjkaukWEslfBAUYfRtxYnecMOU7NG6Y3QY=,iv:jS3lHCIRTyG+xSjK59ZlonLYozlXq+ALKdeUBEX069o=,tag:8B6volU7vfDPeV2YRIIXvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
