---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-kasten-k10
  namespace: flux-system
spec:
  path: ./kubernetes/apps/backup/kasten-k10/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kasten-k10
      namespace: backup
  interval: 30m
  retryInterval: 1m
  timeout: 3m
