apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:rdwtt7r/Jril3x9TkSag0mywXBehus5ZZoByfKccndy/uT0YQWWZvVpAcluSwaDrjBxjEbf9rIkOypXR,iv:9TU1XmLUAmvLKt0dRk0eMbAty7fZQMQvL6OLsj+3qUQ=,tag:4TQYTOCPg6tnt/HKOv1mQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age153gpfdw58csvgxj3vn9ym2g3zx7mfhaldyz5uvvrfajne8htj3asjqrp7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0empzS1pIbW1EVk1ZU3Nq
            NXhxVGpLaExacUwxYUthRjg3aTVwcWNrUG5vCnQvS0twMDEwTTl2VDVLeHZjR0xM
            bVhvWWorS2MrYkx6aXVzOUF1VUlkMlkKLS0tIHRKQm1CNy9ycGNMdHFwdnA4dk1H
            QUxFc0F4UUJDZk56SE1teUIxRmV4QWsKJHo1pi81CjydyhgXQ1BkL409gGIC3i/2
            WzpFhltS4B4rrc8n8uk3Bl4bdbEjQk3WoefvJlb6r/xm2gBNrxtIUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T02:24:37Z"
    mac: ENC[AES256_GCM,data:ZipOv90luHlIauW7UgZOUwu3WVO3pIjyWYwJPujdrAK6PaZYnArb/mkIiGHkHbU8W1zPkBgdsBGH0tvmNybGkQZtbfJPN74M3Yr+opA6Kqb+hd6zkPWEttYadNMnc/YdX+1cOLIX9AJFTR2xiBIba98XpUnMk44e7Pi9Fo7Y7c0=,iv:XWmOmvzDfd3o8P72kzNSj5jUrWumE5V+q8sqyy5vcX8=,tag:WwzPHVvkot1vA83Vf9+qdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
