apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:0ztHEkTCsJmrWYYK0pmopYHtPWglyseia0BsQfyKZ3WnGgPbWGRyd9rP4AwT+evRCq+/Esv7j1Tkf1gE,iv:NXJjQY3WrzPf/VsD4S+W+znYD1B7tQhql3kH0/prfEk=,tag:JdesFSImNEQNBfKeXiF5hQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age153gpfdw58csvgxj3vn9ym2g3zx7mfhaldyz5uvvrfajne8htj3asjqrp7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNHVTeUg3WFRORFI2Wmlv
            QUdFQ2xYUklKWENlZmFMM2poY1FLL2crZldRClQ1QTdObXhBMDJpUDJiOFVzVFk2
            bDJweC9udDlUZmFSOExJNk1xMHpHZTgKLS0tIGRhcmEvYmZ4SGZ4RHlma3hzY3J1
            M3d3RGlRMDUvbjZNZXhybHJLMHFIQXcKDkRX8jrL5h6baWxTgrMYBEI4R5pj/6Jx
            7ATP7W+m74BXhBR8t9hGcdiuZKffMCcDzcpN7qBv7wX+fgPidyqgSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-04T11:59:53Z"
    mac: ENC[AES256_GCM,data:zbQ1lAzpfQREPl9ahp8pzp77fVd2uoMGUeCviRq8V9y10E7D+fU5A85ciHovX8GnX0O4pvCJLdiO8+h85Ucp22yPrmTCBi2M4H1US9pNsSHDbqQtK26yUpEgqKtdpfJxHE5/ntcW05j2HO/Prz0t09sIJSB5l4x2X+oyllJE8eA=,iv:aXRJbdY3uIck3dDPwyWaK1IUUgeV2YN3YjoSbfm0hdY=,tag:kBlPVPuk3Xh0XD6VzaH6tw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
