apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:YrhXVI+RtfiL7cbTk7dNsg2MqFKA6Glj9E0WVetkMKSHnmMGCEXW8/dYQH/wuh5OJJODQ0YiqqPVusVr,iv:YA9s3ADIePaz2UL7fCNWcaZE6yQQxPuDmGCDzzKYoNY=,tag:QJ/sQi7FskVfsUeD/OWo2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age153gpfdw58csvgxj3vn9ym2g3zx7mfhaldyz5uvvrfajne8htj3asjqrp7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyam5Sc0JQbVpyaVdvU0Nz
            MVVWOTZ0cFdnbWUrc0YrYnM0cyt6UmswYVVVCjhKSlBXNnM3ZG4wTWJrZ3lvQ3Yw
            V1dyZVpud0hWdjRsdWY2ejVvaFhpSzQKLS0tIC9Ba1JBN0QxZzAvNURITmZSUkdN
            c2xja1hVTS9YR1c1RTMveFl0SmpOOHcKsi7abHVaC34iB1UpT8qpTClfBdLV/KsD
            JKCo3oMEC1nnSw1r4/Yj2w4zps+UU7thxO5aYfG72p6Zi+yfDvLEDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-14T23:04:29Z"
    mac: ENC[AES256_GCM,data:6OdBSRBz/+CxB24e+VPasfYs3iyB83jslf4Za/L0xnFIUaqYfFIeaK/4z/wAnKSn+GYgyzqQB15NjhDGwW4Zb2rvkKXwiwo1b932o3Uf2Jc5ZA/Q9sGDruM8jsPMnunu0nyQFuZZLr9CVlSyoC8lLXZzauAP3UeNpBsVSBdW9DA=,iv:zciCtymTju08hkk9F4aEYJ7EO9s3g63+AablcSWWnR0=,tag:72hTf+fXXN2hpkhvUvxUZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
