---
cluster:
  name: "home-cluster"
  id: "1"

securityContext:
  privileged: true
  capabilities:
    ciliumAgent: "{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}"
    cleanCiliumState: "{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}"
cgroup:
  autoMount:
    enabled: false
  hostRoot: "/sys/fs/cgroup"

kubeProxyReplacement: "strict"
k8sServiceHost: "home-cluster.strallow.cloud"
k8sServicePort: 6443

ipv4NativeRoutingCIDR: "10.244.0.0/16"

ipam:
  mode: "kubernetes"

operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

hubble:
  enabled: true
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        ingress.home.arpa/type: "internal"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      hosts:
        - "hubble.strallow.cloud"
