---
clusterName: home-cluster
talosVersion: v1.3.6
kubernetesVersion: v1.26.3
endpoint: https://home-cluster.strallow.cloud:6443
domain: strallow.cloud
allowSchedulingOnMasters: true
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
cniConfig:
  name: none
nodes:
  - hostname: k8s-01.strallow.cloud
    ipAddress: 192.168.10.101
    installDisk: /dev/sda
    controlPlane: true
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        dhcp: true
        vip:
          ip: 192.168.10.200
  - hostname: k8s-02.strallow.cloud
    ipAddress: 192.168.10.102
    installDisk: /dev/sda
    controlPlane: true
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        dhcp: true
        vip:
          ip: 192.168.10.200
  - hostname: k8s-03.strallow.cloud
    ipAddress: 192.168.10.103
    installDisk: /dev/sda
    controlPlane: true
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        dhcp: true
        vip:
          ip: 192.168.10.200
  - hostname: k8s-04.strallow.cloud
    ipAddress: 192.168.10.104
    controlPlane: false
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        dhcp: true
controlPlane:
  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
          rotate-server-certificates: "true"
      - op: add
        path: /cluster/proxy
        value:
          disabled: true
      - op: add
        path: /cluster/controllerManager/extraArgs
        value:
          bind-address: 0.0.0.0
      - op: add
        path: /cluster/scheduler/extraArgs
        value:
          bind-address: 0.0.0.0
      - op: remove
        path: /cluster/apiServer/admissionControl
    - |-
      machine:
        network:
          extraHostEntries:
            - ip: 192.168.10.200
              aliases:
                - home-cluster.strallow.cloud
worker:
  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          feature-gates: GracefulNodeShutdown=false,MixedProtocolLBService=false
          rotate-server-certificates: "true"
    - |-
      machine:
        network:
          extraHostEntries:
            - ip: 192.168.10.200
              aliases:
                - home-cluster.strallow.cloud
