clusterName: home-cluster
talosVersion: v1.4.0
kubernetesVersion: v1.27.1
endpoint: https://192.168.10.250:6443
domain: cluster.local
allowSchedulingOnMasters: true
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
cniConfig:
  name: custom
  urls:
    - https://raw.githubusercontent.com/VazardAU/home-ops/main/talos/integrations/cilium/cilium.yaml
additionalMachineCertSans:
  - 192.168.10.250
additionalApiServerCertSans:
  - k8s.strallow.cloud
nodes:
  - hostname: k8s-cp01
    ipAddress: 192.168.10.201
    controlPlane: true
    installDisk: /dev/xvda
    networkInterfaces:
      - interface: eth0
        dhcp: true
  - hostname: k8s-cp02
    ipAddress: 192.168.10.202
    controlPlane: true
    installDisk: /dev/xvda
    networkInterfaces:
      - interface: eth0
        dhcp: true
  - hostname: k8s-cp03
    ipAddress: 192.168.10.203
    controlPlane: true
    installDisk: /dev/xvda
    networkInterfaces:
      - interface: eth0
        dhcp: true
  - hostname: k8s-wk01
    ipAddress: 192.168.10.204
    controlPlane: false
    installDisk: /dev/xvda
    networkInterfaces:
      - interface: eth0
        dhcp: true
  - hostname: k8s-wk02
    ipAddress: 192.168.10.205
    controlPlane: false
    installDisk: /dev/xvda
    networkInterfaces:
      - interface: eth0
        dhcp: true
  - hostname: k8s-wk03
    ipAddress: 192.168.10.206
    controlPlane: false
    installDisk: /dev/xvda
    networkInterfaces:
      - interface: eth0
        dhcp: true
controlPlane:
  patches:
    - |-
      machine:
        time:
          disabled: false
          servers:
            - 192.168.10.1
        kubelet:
          extraArgs:
            rotate-server-certificates: "true"
            feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
      cluster:
        proxy:
          disabled: true
        extraManifests:
          - https://raw.githubusercontent.com/VazardAU/home-ops/main/talos/integrations/cert-approver/cert-approver.yaml
          - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
          - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
          - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
          - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
          - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
          - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
          - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
          - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
          - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
worker:
  patches:
    - |-
      machine:
        time:
          disabled: false
          servers:
            - 192.168.10.1
        kubelet:
          extraArgs:
            rotate-server-certificates: "true"
            feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
