---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Australia/Melbourne"
  METALLB_LB_RANGE: "192.168.10.221-192.168.10.240"
  METALLB_K8S_GATEWAY_ADDR: "192.168.10.210"
  METALLB_INGRESS_ADDR: "192.168.10.220"
