---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-single-replica
parameters:
  ioTimeout: "30"
  protocol: nvmf
  repl: "1"
  fsType: "xfs"
provisioner: io.openebs.csi-mayastor
