---
apiVersion: "openebs.io/v1alpha1"
kind: DiskPool
metadata:
  name: mayastor-node3
  namespace: openebs
spec:
  node: k8s-wk03
  disks: ["/dev/disk/by-id/nvme-CT500P2SSD8_2228E648F04D"]
---
apiVersion: "openebs.io/v1alpha1"
kind: DiskPool
metadata:
  name: mayastor-node2
  namespace: openebs
spec:
  node: k8s-wk02
  disks: ["/dev/disk/by-id/nvme-Samsung_SSD_960_EVO_1TB_S3ETNX0J106272R"]
